Update folder strucutre
flipopay-technologies/identity-service pull request #1
Opened 2024-02-06 06:06 UTC by raam-techie

## Update folder structure

## Ticket no:5 & link: https://tree.taiga.io/project/zubae-payment-gateway/us/5?milestone=377114

## Checklist before requesting a review
- [ ] I have created auth and profile service
- [ ] And update folder structure

2024-02-06 17:46 UTC, afrze requested changes

2024-02-06 17:46 UTC, afrze commented on main.go
> +
Get port from the environment variable. Change message to `Application running in development/production environment on port 8080`.

Fetch the values of port and environment from `.env` file

2024-02-06 18:58 UTC, raam-techie commented
PR changes resolved, Thanks for update!!

2024-02-07 07:45 UTC, afrze approved these changes
LGTM 🚀

2024-02-07 12:15 UTC, merged