Containerize database and service
flipopay-technologies/identity-service pull request #2
Opened 2024-02-06 06:21 UTC by raghul2304

## Containerize database and service

## Ticket number 4 & 6. ticket link 4 = https://tree.taiga.io/project/zubae-payment-gateway/us/4?milestone=377114 & 6 = https://tree.taiga.io/project/zubae-payment-gateway/us/6?milestone=377114 

## Checklist before requesting a review
- [ ] I have created the Dockerfile for auth and profile service 
- [ ] And created the DB container (MongoDB)
- [ ] Written the docker compose file for this services

2024-02-06 17:42 UTC, raam-techie commented on Dockerfile
> +FROM golang:latest
Please specify the Go version used in our application

2024-02-06 17:46 UTC, raam-techie commented on Dockerfile
> +WORKDIR /app
Remove line no:7 WORKDIR  /app [can perform all the necessary operations within a single working directory]

2024-02-06 17:50 UTC, afrze requested changes

2024-02-06 17:50 UTC, afrze commented on docker-compose.yml
> +      - "8080:8080"
Make to add one empty line in all files. This is common for any file, in any language

2024-02-07 05:45 UTC, raghul2304 commented on Dockerfile
> +WORKDIR /app
changes done

2024-02-07 05:46 UTC, raghul2304 commented on docker-compose.yml
> +      - "8080:8080"
changes done

2024-02-07 05:58 UTC, raam-techie approved these changes

2024-02-07 06:53 UTC, Jeyashree46 approved these changes

2024-02-07 07:42 UTC, afrze approved these changes
Look good to me 🚀

2024-02-07 07:43 UTC, merged