Containerization of the DB
flipopay-technologies/identity-service pull request #3
Opened 2024-02-06 10:42 UTC by Jeyashree46

## [DB Containerization](https://tree.taiga.io/project/zubae-payment-gateway/epic/2)
## Ticket 6 - created the dockerfile for db container

## Checklist before requesting a review
- [x] I have pulled the mongodb image 
- [x] And also made changes in the compose file

2024-02-06 17:56 UTC, afrze requested changes
There are more tasks to be done
-  Added config which connects to the db
-  Handle errors if db connection is not going according to plan.

2024-02-06 17:56 UTC, afrze commented on Dockerfile
> +CMD ["/app/main"]
Add an empty line to avoid EOF errors

2024-02-06 17:56 UTC, afrze commented on docker-compose.yml
> +      - '2717:27017'
Add an empty line to avoid EOF errors

2024-02-06 19:41 UTC, raam-techie commented on Dockerfile
> +WORKDIR /app
Remove line 7 WORKDIR /app [can perform all the necessary operations within a single working directory]

2024-02-06 19:41 UTC, raam-techie commented on Dockerfile
> +FROM golang:latest
Please specify the Go version used in our application

2024-02-06 19:43 UTC, raam-techie commented on docker-compose.yml
> +      - '2717:27017'
To keep 27017 instead of 2717

2024-02-07 05:59 UTC, raam-techie approved these changes

2024-02-07 12:08 UTC, closed without merging